install:
    - if [ ! -e /nix ]; then curl https://nixos.org/nix/install | sh; fi
    - source $HOME/.nix-profile/etc/profile.d/nix.sh
    - nix-chanell --list
    - nix-chanell --update
script:
    - cd examples && make
cache:
    directories:
        - /nix
        - /tmp/pypi2nix/cache
