install:
    - if [ ! -e /nix ]; then curl https://nixos.org/nix/install | sh; fi
    - source $HOME/.nix-profile/etc/profile.d/nix.sh
script:
    - cd examples && make
cache:
    directories:
        - /nix
