branches:
  only:
  - master
language: nix
sudo: required
os:
- linux
env:
  global:
    secure: "gEULslaL40LzLDk2SHspXOYbocZVO80YTjmL+iv/E3oZ7QVfz78zwtJgIY7gAX/hSyEfONQ1VtlSAbfZx8zLCSlPlEcGYTt3vKvHD6u0bdPDo2Qp8uINhq9P9diU3JMCSAcNtC72jIcf1cAY/a54aT5DyYwtLB+AxHGUnQjSB+0="
  matrix:
  - EXAMPLE=scipy
  - EXAMPLE=aiohttp
  - EXAMPLE=awscli_and_requests
  - EXAMPLE=connexion
  - EXAMPLE=empy
  - EXAMPLE=flake8
  - EXAMPLE=ldap
  - EXAMPLE=lektor
  - EXAMPLE=mercurial
  - EXAMPLE=pillow
  - EXAMPLE=rss2email
  - EXAMPLE=tornado
install:
- sudo mount -o remount,exec,size=4G,mode=755 /run/user || true
- nix-env -iA nixpkgs.nix-prefetch-git nixpkgs.nix-prefetch-hg
- nix-env -iA cachix -f https://github.com/NixOS/nixpkgs/tarball/889c72032f8595fcd7542c6032c208f6b8033db6
- cachix use pypi2nix
script:
- travis_wait 60 make $EXAMPLE -C ./examples
- cachix push pypi2nix ./examples/$EXAMPLE
stages:
- build
jobs:
  include: 
  - stage: build
    env: EXAMPLE=none
    os: linux
    script:
    - nix build -f ./
    - cachix push pypi2nix ./result
    after_success:
    - nix-build -A coverage
    - ./result-coverage/bin/coverage
  # TODO: cachix takes too long to build on osx
  # - stage: build
  #   env: EXAMPLE=none
  #   os: osx
  #   script: nix-build | cachix push pypi2nix
